services:
  task_manager:    
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
  database:
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: root
    ports:
      - "5432:5432"
    volumes:
      - "./sql:/docker-entrypoint-initdb.d"